# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 20/1/2024, 3:49:14 pm
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
# Export-M365DSCConfiguration `
#   -Components @("IntuneAccountProtectionPolicy") `
#   -Credential $Credential `
#   -Path C:\Users\kapil\projects\lrn_iac\src\microsoft365dsc\config

# Exporting resources using SP
# Export-M365DSCConfiguration `
#   -Components @("IntuneAccountProtectionPolicy") `
#   -ApplicationId "379246f4-c0f6-4364-b60d-f45793394bf1" `
#   -TenantId kapildev1.onmicrosoft.com `
#   -ApplicationSecret "FoG8Q~1W8zrLZz2NadccO0txR3fgSsXJZ5epQcKu" `
#   -Path C:\Users\kapil\projects\lrn_iac\src\dsc

  # explort all Intune related configuration
Export-M365DSCConfiguration `
  -Workloads @("INTUNE") `
  -Credential $Credential `
  -Path C:\Users\kapil\projects\lrn_iac\src\microsoft365dsc\config